---
# handlers file for ansible-role-docker
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
  when: manage_docker_service | bool
  ignore_errors: "{{ ansible_check_mode }}"